name = "decap-proxy"
type = "javascript"

account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2024-06-30"

[vars]
GITHUB_CLIENT_ID = "your-client-id"
GITHUB_CLIENT_SECRET = "your-client-secret"
